apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: python-hello-world-tls
  namespace: my-apps
spec:
  secretName: python-hello-world-tls
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  dnsNames:
    - python-hello-world.localhost
